environment:
  matrix:
    - TOXENV: "3.9-unit"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.7-unit"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.8-unit"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.9-unit"
      TOX_APPVEYOR_X64: 1

    - TOXENV: "3.7-unit"
      TOX_APPVEYOR_X64: 1

    - TOXENV: "3.8-unit"
      TOX_APPVEYOR_X64: 1

build: off

install:
  - "py -3.8 -m pip install -U pip setuptools wheel tox tox-appveyor"

test_script:
  - "py -3.8 -m tox"

cache:
- '%LOCALAPPDATA%\pip\Cache'
